### ISSUE TITLE
Support to define port other than default 2345

### ISSUE THREAD

**Issue by erdosxx** [andreypopp/julia-repl-vim#3]
According to my understanding of this tool, there is currently no configuration file available to define the port number. The default port number, 2345, is hardcoded within the tool. 
However, occasionally when I use this tool with others on the same remote server, we encounter interference problems due to the shared default port number. 
I would like to suggest adding support for a configuration file that allows users to define their desired port number. Alternatively, if this feature already exists, it would be helpful to include instructions on how to configure it in the README.md file. 
This would enhance the usability and flexibility of the tool, preventing conflicts and improving the overall user experience.
I suggest two ways to solve this issue.
1. Add to support config file to define port number
2. Can define port number in command line.

**Comment by ArbitRandomUser** [comment]
ive made a PR for this ,
comments on improvements welcome
, https://github.com/andreypopp/julia-repl-vim/pull/4

**Comment by andreypopp** [comment]
#4 merged
